# only use in development.
version: '3.8'

services:
  mysql:
    image: mysql:5.7.31
    container_name: python-practice
    hostname: python-practice
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=python
      - MYSQL_USER=python
      - MYSQL_PASSWORD=python
      - MYSQL_TCP_PORT=3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
